local vim = vim

vim.api.nvim_set_keymap('', '<leader>ev', [[<cmd>exe 'edit' $MYVIMRC<cr>]],  { noremap = true, silent = true })

vim.api.nvim_set_keymap('', '<up>', '<Nop>',  { noremap = true, silent = true })
vim.api.nvim_set_keymap('', '<down>', '<Nop>',  { noremap = true, silent = true })
vim.api.nvim_set_keymap('', '<left>', '<Nop>',  { noremap = true, silent = true })
vim.api.nvim_set_keymap('', '<right>', '<Nop>',  { noremap = true, silent = true })
vim.api.nvim_set_keymap('i', '<up>', '<Nop>',  { noremap = true, silent = true })
vim.api.nvim_set_keymap('i', '<down>', '<Nop>',  { noremap = true, silent = true })
vim.api.nvim_set_keymap('i', '<left>', '<Nop>',  { noremap = true, silent = true })
vim.api.nvim_set_keymap('i', '<right>', '<Nop>',  { noremap = true, silent = true })
vim.api.nvim_set_keymap('i', '<c-h>', '<left>',  { noremap = true, silent = true })
vim.api.nvim_set_keymap('i', '<c-j>', '<down>',  { noremap = true, silent = true })
vim.api.nvim_set_keymap('i', '<c-k>', '<up>',  { noremap = true, silent = true })
vim.api.nvim_set_keymap('i', '<c-l>', '<right>',  { noremap = true, silent = true })

vim.api.nvim_set_keymap('', '<c-j>', '<c-w>j',  { silent = true })
vim.api.nvim_set_keymap('', '<c-k>', '<c-w>k',  { silent = true })
vim.api.nvim_set_keymap('', '<c-l>', '<c-w>l',  { silent = true })
vim.api.nvim_set_keymap('', '<c-h>', '<c-w>h',  { silent = true })
vim.api.nvim_set_keymap('v', '<up>', '<Nop>',  { noremap = true, silent = true })
vim.api.nvim_set_keymap('v', '<down>', '<Nop>',  { noremap = true, silent = true })
vim.api.nvim_set_keymap('v', '<left>', '<Nop>',  { noremap = true, silent = true })
vim.api.nvim_set_keymap('v', '<right>', '<Nop>',  { noremap = true, silent = true })
vim.api.nvim_set_keymap('i', 'jk', '<esc>',  { noremap = true, silent = true })
vim.api.nvim_set_keymap('i', 'kj', '<esc>',  { noremap = true, silent = true })
vim.api.nvim_set_keymap('v', 'jk', '<esc>',  { noremap = true, silent = true })
vim.api.nvim_set_keymap('v', 'kj', '<esc>',  { noremap = true, silent = true })
vim.api.nvim_set_keymap('c', 'jk', '<esc>',  { noremap = true, silent = true })
vim.api.nvim_set_keymap('c', 'kj', '<esc>',  { noremap = true, silent = true })
vim.api.nvim_set_keymap('c', '<c-p>', '<up>',  { noremap = true, silent = true })
vim.api.nvim_set_keymap('c', '<c-n>', '<down>',  { noremap = true, silent = true })


